### ISSUE TITLE
Multistart optimization with parameter constraints

### ISSUE THREAD

**Issue by aidinbii** [ICB-DCM/pyPESTO#1334]
Hello, is there a way to specify parameter constraints for parameter estimation.
For example, if I have a parameter vector: (p1, p2, p3, p4). And I want a constraint: p2 <= p3.

Similar to [this](https://www.mathworks.com/help/releases/R2022a/optim/ug/fmincon.html)

Thank you

**Comment by Doresic** [comment]
Hi aidinbii,

In the current implementation, parameter-dependent constraints are not allowed.

However, there is an easy way to go around this problem. In your model, you can define the p3 parameter using the following assignment rule p3 := p2 + p23_diff. Then if you estimate the two parameters p2 and p23_diff, you can satisfy the p2<=p3 bound by setting the lower bound for p23_diff to 0. 

Hope this helps.

Best,
Domagoj

**Comment by aidinbii** [comment]
@Doresic, thanks for the reply
But, will it work together with conditions?

For instance:

``` 
odes:
    - stateId: mu_1
      rightHandSide: -Ka*mu_1
      initialValue: 0

    - stateId: mu_2
      rightHandSide: Ka*mu_1 - Ke*mu_2
      initialValue: 0

parameters:
    - parameterId: Ka
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 0

    - parameterId: Ke
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 0

    - parameterId: VdF
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 0

    - parameterId: Ka_3
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1

    - parameterId: Ka_30
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1

    - parameterId: Ka_100
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1 

    - parameterId: Ke_3
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1

    - parameterId: Ke_30
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1

    - parameterId: Ke_100
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1

    - parameterId: VdF_3
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1

    - parameterId: VdF_30
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1

    - parameterId: VdF_100
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.0001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1
    
    - parameterId: diff_Ke1
      nominalValue: 0.1
      parameterScale: log
      lowerBound: 0.000001
      upperBound: 10
      initializationPriorType: uniform
      initializationPriorParameters: 0.05; 1
      estimate: 1


assignments:
    - assignmentId: Ke_3
      formula: Ke_30 + diff_Ke1

conditions:
    - conditionId: dose_3
      Ka: Ka_3
      Ke: Ke_3
      VdF: VdF_3
      mu_1: 3e+6 

    - conditionId: dose_30
      Ka: Ka_30
      Ke: Ke_30
      VdF: VdF_30
      mu_1: 30e+6

    - conditionId: dose_100
      Ka: Ka_100
      Ke: Ke_100
      VdF: VdF_100
      mu_1: 100e+6
```
